### ISSUE TITLE
Project Tasks

### ISSUE THREAD

**Issue by R1TE5H** [R1TE5H/SSW345-FinalProject#4]
# Tasks
- [x] Update the driver class to take the user through both use-cases from the report

# Report
**Diagrams** 
- [x] Profile Diagrams
- [x] Class Diagram -- Screenshots of how the class diagram maps to the code
- [x] Object Diagram
- [x] 2 Use Case Diagram
- [x] Component Diagram
- [x] Deployment Diagram
- [x] Package Diagram
- [x] Composite Structure Diagrams
- [x] Activity Diagrams
- [x] Sequence Diagrams
- [x] Interaction Diagrams
- [x] Communication Diagrams
- [x] Timing Diagrams
- [x] State Machine Diagrams

**Chapters**
- [x] Title Page
- [x] History Table
- [x] List of Figures
- [x] List of Tables
- [ ] Relevant Chapters
- [x] Agile Development Chapter
- [x] Reflection Chapter -- What was completed, optimizations, areas to grow in event of continuing project
- [x] Bibliography
- [ ] Index

**Other**
- [ ] Design Pattern --> Singleton Pattern
- [ ] Aim to look professional -- scale pictures properly, put stuff in proper chapters...

# Presentation
**Diagrams**
- [x] Classes
- [x] 2 Use Cases
- [x] Deployment
- [x] 2 Activity Diagram
- [x] State Machine Diagram
- [x] Sequence Diagram
- [x] Timing Diagram

**Documents**
- [x] Use Case Tables
- [x] Requirement Tables
- [x] Class Component Slide
- [x] Miscellaneous 

**Code**
- [x] Video Recording of Code Working
